### ISSUE TITLE
skill shot animation doesn't always show

### ISSUE THREAD

**Issue by GabeKnuth** [GabeKnuth/BnD#14]
It looks like it shows up for a split second, then gives way to the background

**Comment by GabeKnuth** [comment]
This may be related to the logging causing lag. Might not appear since I switched to bash.

**Comment by GabeKnuth** [comment]
This still seems to be a problem, though the cause might be different now. Sometimes all I see is the bnd_background image on the stage. I feel like it was working really well until today.

@toomanybrians added you just in case you've seen this too

**Comment by toomanybrians** [comment]
It seems to me that this is due to a bad switch, where the switch is getting hit (by vibration or something?) and that's registering the ball on the pf and ending the skillshot. Can you look at the switch activity when this happens next time?

**Comment by GabeKnuth** [comment]
It could be the drop target switch that I fixed last night. Not sure if I ran the game after I fixed it. I'll check it out.
