### ISSUE TITLE
MC getting invalid commands. Also MPF is crashing with serial comms problem.

### ISSUE THREAD

**Issue by GabeKnuth** [GabeKnuth/BnD#30]
Logs attached. Happens repeatedly during Bonus when hitting both flippers. I can pretty much always get it to do it if I hit both flippers a few times.

[Archive 10.zip](https://github.com/GabeKnuth/BnD/files/871511/Archive.10.zip)

**Comment by toomanybrians** [comment]
The MC getting invalid commands appears to be cosmetic. I updated dev to fix this.

**Comment by GabeKnuth** [comment]
comm crash seems to be a stupid f-ing cabling thing. I mean seriously, how many times can we get bit by noise in our lives??
