### ISSUE TITLE
Manager's Choice didn't hold ball when starting poker mode. need to behave just like hole.

### ISSUE THREAD

**Issue by GabeKnuth** [GabeKnuth/BnD#42]
@Brian can you wire this up like you did the other modes? The bd_top_kicker ball device should be holding on to the ball just like the lower vuk does...just without having to service any other things (like hilo or mystery)

**Comment by toomanybrians** [comment]
Since manager's choice can potentially start any of the 5 main modes, it should have a ball hold that uses the same release event as the lower left vuk

**Comment by toomanybrians** [comment]
I think this is done? @GabeKnuth did you add the top vuk ball hold after this issue was created? Because it seems fine as it is in the configs now to me based on what you did?
