### ISSUE TITLE
Also for random_event_player, can we add weight to events?

### ISSUE THREAD

**Issue by GabeKnuth** [GabeKnuth/BnD#56]
It would be cool to use random_event_player the same way sound_pools are used, where you can add a weight to each sound in the pool if you wanted some to play more often than others.

An example use would be the Mystery mode that picks random awards via random_event_player. I'd like it to post the event to hold the album value more often than the one that awards an extra ball.

**Comment by jabdoa2** [comment]
That should be easy. Maybe this also already works.
